name:          Fast Web Media Coding Standards Guide
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://codeguide.fwm.cx

markdown:      rdiscount
permalink:     pretty
pygments:      true
